### ISSUE TITLE
Suggestion: Saving theme in a cookie

### ISSUE THREAD

**Issue by romangraef** [Hallo89/hallo89.net#2]
Saving the theme in a cookie which might also be used apart from the homepage. This might be achieved by using a more general css file for all pages (If that is not the case since i last checked).

**Comment by Hallo89** [comment]
That's a very good idea I never got to implement, however now that I need to make a cookie banner anyways since Cloudflare is using one, it's a good time to do it! Making those global is also a good suggestion (Given that I will implement a light mode on other pages as well but I think the blog is a good place for that)

**Comment by Hallo89** [comment]
Implemented in https://github.com/Hallo89/hallo89.net/commit/96e22a357247d8ece5d0beb640c86d332f5bb3d4 and the following commits!
